appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: YLhuzrBaSNKrPY92WZxC8Ty2llYAG9nIpLAE0E7APB8dsx/2YhZpsv2o+bUB7OWpJ3IyOYRvKwDJdScqpkDCwdyn2sv6Xrz/UR+6E6ZiLcxAxiI0IOLcapJlF/9o3dismdwImeBwzb38kF94eKt7tVj3+T3NyEUrdgsydbMieiOLqEcFbeduMCtwHraZws8pubi9WXWRXJZ3ui6Wo60/v6zX7TpgjPsZGxyKikxG67xaMRMhAU1bKgePsGPjK5AjDIgyJLx2b9tCFXi2bMqcrNU9MI1Ph7AkOVE+n2B5BDIrcMXz97gYdMYPfbE3Iv5vYbHsfUGXndqGDoemnFkrSNhM3IFe7TQQ4Q/Wt/T7WT5zNjwyXu1B+jeLEGX9eyDjLP5aQajxObuIfFU7cabztVnsPwnoVP2RvJqwZgQADgVScR/C5SWQrjC10wdn+38MFluAxNv+CG+Ip5YkiuXmCuPSUGiUhaT8wbMsYt/fh4ZYZpa+2iCd67M935zJ34fRdqxgmXWvyzpBISSAlSei1NNHdDgb4ohbKvFxu87sG2lbRiJfbkrtSqQaFf1beNxge9DsjnlGEP07rpn34qCukOhgQcypPOJJp09TsjZeV4FYgA5PMwYfZGESDily/dSNYEhVFdwO0v1sPe89wtTn+idogW1vooMzCMgqasLuL4M=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
